language: android

jdk:
  - openjdk7

sudo: false

android:
  components:
    - tools
    - android-22
    - build-tools-23.0.1
    - extra-android-m2repository

cache: false

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
  # Download and show android dependencies
  # - ./gradlew androidDependencies

script:
  - ./gradlew clean build connectedCheck
